config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "top#show"
  devise_for :slide_shows, controllers: {
    registrations: "slide_shows/registrations",
    sessions: "slide_shows/sessions"
  }
  resources :slide_shows, only: [:show, :edit, :update] do
    namespace :api, format: "json" do
      resources :slides, only: [:index]
    end
  end
  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/element_type.rb
# frozen_string_literal: true

class ElementType < ApplicationRecord
  has_many :slides
end

app/models/image_processor.rb
# frozen_string_literal: true

require "mini_magick"
require "tempfile"

class ImageProcessor
  def initialize(slide, url)
    @slide = slide
    @image = arrange_size(MiniMagick::Image.open(url))
    @text = reshape_text(slide.arranged_text)
  end

  def execute
    result = draw_text(put_belt(@image), @text)
    Tempfile.create do |f|
      result.write f
      @slide.image = MiniMagick::Image.open(f)
      @slide.save
    end
  end

  private
    def reshape_text(text)
      text.scan(/.{1,#{Constants::INDENTION_COUNT}}/)[0...Constants::ROW_LIMIT].join("\n")
    end

    def arrange_size(image)
      image.combine_options do |config|
        config.background Constants::BACKGROUND
        config.gravity Constants::GRAVITY
        config.resize Constants::FRAME_SIZE
        config.extent Constants::FRAME_SIZE
      end
    end

    def put_belt(image)
      image.composite(Constants::BELT) do |config|
        config.compose "Multiply"
        config.geometry Constants::BELT_POSITION
      end
    end

    def draw_text(image, text)
      image.combine_options do |config|
        config.gravity Constants::GRAVITY
        config.font Constants::FONT
        config.pointsize Constants::FONT_SIZE
        config.draw "text #{Constants::TEXT_POSITION} '#{text}'"
      end
    end
end

app/models/slide.rb
# frozen_string_literal: true

class Slide < ApplicationRecord
  belongs_to :slide_show
  belongs_to :element_type
  mount_uploader :image, ImagesUploader

  scope :filter_by_slide_show, ->(slide_show_id) do
    where(slide_show_id: slide_show_id, active: true).where.not(image: nil) if slide_show_id
  end

  def arranged_text
    if element_type.id == 1
      search_word
    else
      element_type.column_name + "：\n" + search_word + before_word + after_word
    end
  end

  def search_target?
    active == true && search_word != ""
  end
end

app/models/slide_collection.rb
# frozen_string_literal: true

require "google/apis/customsearch_v1"
require "open-uri"

class SlideCollection
  def initialize(slides)
    @slides = slides
  end

  def process_images
    @slides.each do |slide|
      if slide.element_type_id == 1
        @url = Constants::COVER
      else
        @url = fetch_image_url(slide.search_word)
      end
      image_processor = ImageProcessor.new(slide, @url)
      image_processor.execute
    end
  end

  private
    def fetch_image_url(search_word)
      searcher = Google::Apis::CustomsearchV1::CustomsearchService.new
      searcher.key = ENV["API_KEY"]
      results = searcher.list_cses(search_word, cx: ENV["CSE_ID"], search_type: "image", num: 1, start: 1)
      results.items[0].link
    end
end

app/models/slide_show.rb
# frozen_string_literal: true

class SlideShow < ApplicationRecord
  has_many :slides
  accepts_nested_attributes_for :slides
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, authentication_keys: [:show_name]
  attr_accessor :login
  validates :show_name,
  uniqueness: { case_sensitive: :false },
  length: { minimum: 4, maximum: 20 },
  format: { with: /\A[a-z0-9]+\z/, message: "スライドショーIDは4~20文字の半角英数字です" }

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/api/slides_controller.rb
# frozen_string_literal: true

class API::SlidesController < ApplicationController
  def index
    render json: Slide.filter_by_slide_show(params[:slide_show_id]).select(:id, :image).sort
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      added_attrs = %i[show_name login]
      devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
      devise_parameter_sanitizer.permit(:sign_in, keys: added_attrs)
    end
end

app/controllers/slide_shows/registrations_controller.rb
# frozen_string_literal: true

class SlideShows::RegistrationsController < Devise::RegistrationsController
  protected
    def after_sign_up_path_for(resource)
      edit_slide_show_path(resource)
    end
end

app/controllers/slide_shows/sessions_controller.rb
# frozen_string_literal: true

class SlideShows::SessionsController < Devise::SessionsController
  protected
    def after_sign_in_path_for(resource)
      resource
    end

    def after_sign_out_path_for(resource)
      new_slide_show_registration_path
    end
end

app/controllers/slide_shows_controller.rb
# frozen_string_literal: true

class SlideShowsController < ApplicationController
  before_action :set_slide_show, only: %i[show edit update]
  before_action :require_authentication

  def show
  end

  def edit
    require_empty_image_slides
  end

  def update
    if @slide_show.update(slide_show_params)
      slides = @slide_show.slides.select { |s| s.search_target? }
      ImageProcessorJob.perform_later(slides) if slides.any?
      redirect_to @slide_show
    else
      render :edit
    end
  end

  private
    def set_slide_show
      @slide_show = SlideShow.find(params[:id])
    end

    def slide_show_params
      params.require(:slide_show).permit(:show_name, slides_attributes: [:element_type_id, :search_word, :before_word, :after_word, :active])
    end

    def require_empty_image_slides
      if @slide_show.slides.any?
        redirect_to @slide_show, alert: "すでにスライドショーを作成済みです"
      else
        @slide_show.slides.build
      end
    end

    def require_authentication
      if @slide_show != current_slide_show
        redirect_to root_path, alert: "スライドショーIDとパスワードの入力が必要です"
      end
    end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def show
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SelfSlide
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
  body
    p#alert
      = alert.html_safe if alert
    = yield

app/views/slide_shows/_form.html.slim
= form_for @slide_show do |f|
  - if @slide_show.errors.any?
    #error_explanation
      h2 = "#{pluralize(@slide_show.errors.count, "error")} エラーのため保存してません:"
      ul
        - @slide_show.errors.full_messages.each do |message|
          li = message

  table
    thead
      tr
        th 作成
        th 項目名
        th 入力欄1
        th 入力欄2
        th 対象年
    tbody
      = f.fields_for :slides do |g|
        tr
          td
            = g.check_box :active, checked: true
          td
            | スライドショータイトル
          td
            = g.text_field :search_word, placeholder: "（例）田中大輔の自己紹介スライドショー", size: 40
          td
            | -
          td
            | -
        = g.hidden_field :element_type_id, value: 1
      = f.fields_for :slides do |h|
        tr
          td
            = h.check_box :active, checked: true
          td
            | 学歴1（卒業高校）
          td
            = h.text_field :search_word, placeholder: "（例）六甲学院高等学校", size: 40
          td
            | -
          td
            = h.select :after_word, options_for_select((1980..2020).map{|n| ["#{n}年", "\n（#{n}年卒業）"] }, "\n（2000年卒業）")
            | 卒業
        = h.hidden_field :element_type_id, value: 2

      = f.fields_for :slides do |i|
        tr
          td
            = i.check_box :active, checked: true
          td
            | 学歴2（卒業大学/学部）
          td
            = i.text_field :search_word, placeholder: "（例）大阪大学経済学部", size: 40
          td
            | -
          td
            = i.select :after_word, options_for_select((1980..2020).map{|n| ["#{n}年", "\n（#{n}年卒業）"] }, "\n（2000年卒業）")
            | 卒業
        = i.hidden_field :element_type_id, value: 3

      = f.fields_for :slides do |j|
        tr
          td
            = j.check_box :active, checked: true
          td
            | 職歴1
          td
            = j.text_field :search_word, placeholder: "（例）エムスリー株式会社", size: 40
          td
            | -
          td
            = j.select :after_word, options_for_select((1980..2020).map{|n| ["#{n}年", "\n（#{n}年入社）"] }, "\n（2000年入社）")
            | 入社
          td
        = j.hidden_field :element_type_id, value: 4

      = f.fields_for :slides do |k|
        tr
          td
            = k.check_box :active, checked: true
          td
            | 職歴2
          td
            = k.text_field :search_word, placeholder: "（例）ANNONE株式会社", size: 40
          td
            | -
          td
            = k.select :after_word, options_for_select((1980..2020).map{|n| ["#{n}年", "\n（#{n}年入社）"] }, "\n（2000年入社）")
            | 入社
        = k.hidden_field :element_type_id, value: 5

      = f.fields_for :slides do |l|
        tr
          td
            = l.check_box :active, checked: true
          td
            | 免許/資格1：
          td
            = l.text_field :search_word, placeholder: "（例）普通自動車", size: 40
          td
            = l.text_field :before_word, placeholder: "（例）免許", size: 30
          td
            = l.select :after_word, options_for_select((1980..2020).map{|n| ["#{n}年", "\n（#{n}年取得）"] }, "\n（2000年取得）")
            | 取得
        = l.hidden_field :element_type_id, value: 6

      = f.fields_for :slides do |m|
        tr
          td
            = m.check_box :active, checked: true
          td
            | 免許/資格2：
          td
            = m.text_field :search_word, placeholder: "（例）TOEIC/英検", size: 40
          td
            = m.text_field :before_word, placeholder: "（例）990点/準一級", size: 30
          td
            = m.select :after_word, options_for_select((1980..2020).map{|n| ["#{n}年", "\n（#{n}年取得）"] }, "\n（2000年取得）")
            | 取得
        = m.hidden_field :element_type_id, value: 7

      = f.fields_for :slides do |n|
        tr
          td
            = n.check_box :active, checked: true
          td
            | 趣味：
          td
            = n.text_field :search_word, placeholder: "（例）サイクリング", size: 40
          td
            | -
          td
            | -
        = n.hidden_field :element_type_id, value: 8

      = f.fields_for :slides do |o|
        tr
          td
            = o.check_box :active, checked: true
          td
            | 特技：
          td
            = o.text_field :search_word, placeholder: "（例）ジャグリング", size: 40
          td
            | -
          td
            | -
        = o.hidden_field :element_type_id, value: 9

  br
  .actions
    = f.submit "スライドショーを作成"
  | スライドショーの作成〜完成まで10~30秒程度かかります。
  br
  | 戻るボタンなどを押さず、そのままお待ちください。

app/views/slide_shows/edit.html.slim
h1 自己紹介内容を作成

h4 ※入力欄1に記入されたキーワードでGoogle画像検索を行い、スライドを作成します
h4 ※スライド作成は、一度送信すると取消や編集することができませんのでご注意ください
h4 （新しく作り直すことは可能です）

= render "form"
br
= link_to "トップページへ戻る", root_path

app/views/slide_shows/show.html.slim
h1 スライドショーページ

- if @slide_show.slides.where.not(image: nil).any?
  .test#slide
    slide :slide-show-id=@slide_show.id
- elsif @slide_show.slides.any?
  | まだスライド作成が完了していません。30秒ほどお待ちいただき、ページを再度リロードください。
- else
  | まだスライドが作成されていません。
  br
  = link_to "項目を入力してスライドショーを作成", edit_slide_show_path(current_slide_show)
br
br
= link_to "トップページへ戻る", root_path

app/views/top/show.html.slim
h2
  strong 自己紹介スライドかんたん作成サービス

h4
  br
  | 本サービスは、項目にキーワードを入力するだけで、
  br
  | 簡単に自己紹介スライドショーが作成できるサービスです。
  br
  br
  | 作成したスライドのIDとパスワードを共有すれば、
  br
  | 他の人と異なるブラウザ、デバイスでスライドページを共有しながら閲覧することが可能です。

h2
  br
  | イメージ動画
  br
  = video_tag("introduction.mp4", muted: true, controls: true, width: "700")

h3
  - if current_slide_show
    = link_to "新たなスライドショーを作成", destroy_slide_show_session_path, method: :delete
    br
    br
    = link_to "スライドショーを見る", current_slide_show

  - else
    = link_to "新たなスライドショーを作成", new_slide_show_registration_path
    br
    br
    = link_to "IDとパスワードを入力してスライドショーを見る", new_slide_show_session_path